"""Add perspective_analysis column

Revision ID: 45b056a4ba3c
Revises: 6f93291f8212
Create Date: 2026-01-31 14:56:30.911032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b056a4ba3c'
down_revision: Union[str, Sequence[str], None] = '6f93291f8212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('small_voice_score', sa.Float(), nullable=True))
    # op.add_column('analysis_sessions', sa.Column('perspective_analysis', sa.Text(), nullable=True)) # Removed by user request
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('analysis_sessions', 'perspective_analysis')
    op.drop_column('analysis_results', 'small_voice_score')
    # ### end Alembic commands ###
